### ISSUE TITLE
Swap human readable summary for full CC0 LICENSE.md text?

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/.github#1]
## Issue Report

Swap human readable summary for full CC0 LICENSE.md text?

### Expected behavior

If we use vanilla/un-modified LICENSE text, we get a sweet explainer at the top of the page, and we get a nice element in the sidebar of the repo page itself (see screenshot.)

### Actual behavior

Current, we have a human-readable summary instead.

### Steps to reproduce the behavior

See Screenshot
<img width="852" alt="Screenshot 2023-12-27 at 1 23 19 PM" src="https://github.com/DSACMS/.github/assets/107957201/f42b94a9-554e-49bd-9677-b4ce5fdef2f4">

**Comment by decause-gov** [comment]
7/22:
- We now just need to update this repo wholesale, now that repo-scaffolder exists!

**Comment by decause-gov** [comment]
07/29:
- This is now updated in .github to use the vanilla CC0 text!
- Will merge next week!

**Comment by decause-gov** [comment]
07/29:
- Goal: Merge!

**Comment by decause-gov** [comment]
08/02:
- after the .github PR is merged, this is done too!

**Comment by natalialuzuriaga** [comment]
09/05:
- Donezo! Closing
