### ISSUE TITLE
Update .github templates with latest repolinter configs

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/.github#3]
Now that we have our new repolinter.json configs, we should add them to the .github template repository.

Question: should we have a template for each tier?

**Comment by decause-gov** [comment]
07/29:
A: No, we're going to standardize on Tier3 instead of having multiple tiers in .github.

- @natalialuzuriaga updated the .github repo to use the new Tier3 templates!
- PR Open. Need to re-add the `insert-license-headers.sh` files, then we're good to merge!

**Comment by decause-gov** [comment]
07/29:
- ACTION: update the PR
- GOAL: Merge!

**Comment by decause-gov** [comment]
08/02:
- Added the license headers script back to it.
- PR is ready for review @decause-gov

**Comment by natalialuzuriaga** [comment]
09/05:
- Templates have been added, closing ticket
